config/routes.rb
GoodsMaster::Application.routes.draw do
  constraints(subdomain: /.+/) do
    devise_for :users, path: "/",
               controllers: { registrations: 'users/registrations',
                              sessions: 'users/sessions',
                              invitations: 'users/invitations'},
               skip: [:registrations, :sessions, :invitations, :passwords]

      devise_scope :user do
        # Sign in/out works global wide.
        get '/signin'   => "users/sessions#new",        as: :new_user_session
        post '/signin'  => 'users/sessions#create',     as: :user_session
        get '/signout'  => 'users/sessions#destroy',    as: :destroy_user_session if Devise.sign_out_via == :get
        delete '/signout'  => 'users/sessions#destroy', as: :destroy_user_session


        # Routes signup and acknowledgement routes only under app subdomain
        constraints(subdomain: Settings.app_subdomain) do
          devise_for :users, controllers: { passwords: "users/passwords" },
            skip: [:registrations, :sessions, :invitations]
          get "/signup"  => "users/registrations#new",       as: :new_user_registration
          post "/signup" => "users/registrations#create",    as: :user_registration
          get "/signup/thankyou" => "users/registrations#acknowledgement", as: :signup_acknowledgement
        end

        # Todo: refactor to Subdomain class when will be more than one application subdomain
        constraints(lambda { |req| !(req.subdomain == Settings.app_subdomain) }) do
          get "/profile/edit" => "users/registrations#edit", as: :edit_user_registration
          put "/profile"  => "users/registrations#update"

          get 'memberships/invitation/accept' => "users/invitations#edit",   as: :accept_user_invitation
          put 'memberships/invitation'        => "users/invitations#update", as: :user_invitation
        end
      end

    # Within accounts subdomains
    constraints(lambda { |req| !(req.subdomain == Settings.app_subdomain) }) do
      resource :account, only: [:edit, :update]
      resources :memberships, except: [:show, :new, :create]
      get 'memberships/invitation/new' => "memberships#new",    as: :new_membership
      post 'memberships/invitation'    => "memberships#create", as: :membership_invitation

      get '/products/:id/versions/:version' => "products#show", :as => :product_version
      resources :products do
        get 'autocomplete/:field' => "products#autocomplete", as: :autocomplete, on: :collection

        resources :comments, only: [:create, :destroy]
        resources :photos, only: [:show, :create, :destroy]
      end
    end

    # Within app subdomain
    constraints(subdomain: Settings.app_subdomain) do
      namespace :users, path: "/signup" do
        resource :account, only: [:new, :create]
      end

      namespace :users, path: "/signin" do
        resources :accounts, only: :index
      end

      scope subdomain: Settings.app_subdomain do
        devise_for :admins, path: 'dashboard', controllers: { sessions: 'admin/sessions' }, format: false

        resources :admins, only: [:edit, :update], :module => "admin", :path => "dashboard/admins"

        namespace :admin, path: "dashboard" do
          resources :accounts, only: [:index, :show] do
            get :activate, on: :member
            get :login_as_owner, on: :member
          end

          resources :events, only: :index

          get '/' => 'dashboard#index', as: :dashboard
          root :to => 'dashboard#index', as: :root
        end
      end
    end

    get '/'  => 'home#index', as: :home
    root :to => 'home#index', as: :root
  end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/partials/_account_menu.html.haml
%ul.nav{class: "secondary-nav"}
  %li.dropdown{"data-dropdown" => "dropdown"}
    %a{class: "dropdown-toggle"}
      = t('navigation.account.menu_title')
    = render_navigation context: :account

app/views/layouts/partials/_admin_menu.html.haml
%ul.nav{class: "secondary-nav"}
  %li.dropdown{"data-dropdown" => "dropdown"}
    %a{class: "dropdown-toggle"}
      = current_admin.email
    = render_navigation context: :admin

app/views/layouts/partials/_copyright.html.haml
%span.copyright
  &copy
  = Settings.copyright
  = "#{Time.now.year}"

app/views/layouts/partials/_flash.html.haml
- flash.each do |key, value|
  - unless value.blank?
    .flash.alert-message.block-message.fade.in{ class: "#{key}", :"data-alert" => "#{key}" }
      %a.close{ href: "#" }×
      %p= value

app/views/layouts/partials/_head.html.haml
%meta{"http-equiv" => "content-type", :content => "text/html; charset=utf-8"}
%meta{:name => "robots", :content => "noindex, nofollow"}
%meta{:name => "keywords", :content => ""}
%meta{:name => "description", :content => ""}
%title= "#{Settings.project_name}#{": #{yield(:head_title)}" if content_for?(:head_title)}"
= stylesheet_link_tag "application"
= javascript_include_tag "application"
= user_voice_widget
= csrf_meta_tags
= favicon_link_tag
%script I18n.defaultLocale = "#{I18n.default_locale}"; I18n.locale = "#{I18n.locale}";

app/views/layouts/partials/_user_menu.html.haml
%ul.nav{class: "secondary-nav"}
  %li.dropdown{"data-dropdown" => "dropdown"}
    %a{class: "dropdown-toggle"}
      = (current_user.first_name || current_user.email)
    = render_navigation context: :user